#!/usr/bin/env bash
# install nginx on a remote server
# and configure it to serve a simple hello world

apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
service nginx start
