#!/usr/bin/env bash

nginx_conf='/etc/nginx/sites-available/default'

new_conf="location /old_path {
    rewrite ^/old_path(.*) http://www.google.com permanent;
}

location / {
    try_files \$uri \$uri/ =404;
}"

sed -i "/location \/ {/,/}/{c\\$new_conf" $nginx_conf

service nginx restart
