#!/bin/bash
# Update the package list
sudo apt-get update
# Install Nginx
sudo apt-get install -y nginx
# Get the hostname of the server
hostname_value=$(hostname)

# Create a custom configuration file for Nginx
echo 'server {' | sudo tee /etc/nginx/sites-available/default
echo '    listen 80 default_server;' | sudo tee -a /etc/nginx/sites-available/default
echo '    server_name _;' | sudo tee -a /etc/nginx/sites-available/default
echo "    add_header X-Served-By $hostname_value;" | sudo tee -a /etc/nginx/sites-available/default
echo '    location / {' | sudo tee -a /etc/nginx/sites-available/default
echo '        # Your additional configuration if needed' | sudo tee -a /etc/nginx/sites-available/default
echo '    }' | sudo tee -a /etc/nginx/sites-available/default
echo '}' | sudo tee -a /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
