#!/usr/bin/env bash
# installs and configures an HAproxy
apt-get update -y
apt-get install haproxy -y

echo "frontend web-frontend" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "    bind *:80" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "    default_backend web-backend" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "backend web-backend" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "    balance roundrobin" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "    server web-01 3441-web-01:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "    server web-02 3441-web-02:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg


sudo /etc/init.d/haproxy restart
