#!/usr/bin/env bash
#checking if nginx is listening on port 80 and running

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
