#!/usr/bin/env bash

# Step 1: Access the Docker container
docker exec -it 47ca3994a491 /bin/bash

# Step 2: Navigate to Apache Configuration Directory
cd /etc/apache2/sites-available

# Step 3: Edit the Default Configuration File
echo '<VirtualHost *:80>' > 000-default.conf
echo '    DocumentRoot /var/www/html' >> 000-default.conf
echo '    ServerName localhost' >> 000-default.conf
echo '' >> 000-default.conf
echo '    <Directory /var/www/html>' >> 000-default.conf
echo '        Options Indexes FollowSymLinks' >> 000-default.conf
echo '        AllowOverride None' >> 000-default.conf
echo '        Require all granted' >> 000-default.conf
echo '    </Directory>' >> 000-default.conf
echo '' >> 000-default.conf
echo '    ErrorLog ${APACHE_LOG_DIR}/error.log' >> 000-default.conf
echo '    CustomLog ${APACHE_LOG_DIR}/access.log combined' >> 000-default.conf
echo '</VirtualHost>' >> 000-default.conf

# Step 4: Navigate to DocumentRoot Directory
cd /var/www/html

# Step 5: Create or Edit the Index.html File
echo '<!DOCTYPE html>' > index.html
echo '<html>' >> index.html
echo '<head>' >> index.html
echo '    <title>Hello Holberton</title>' >> index.html
echo '</head>' >> index.html
echo '<body>' >> index.html
echo '    <h1>Hello Holberton</h1>' >> index.html
echo '</body>' >> index.html
echo '</html>' >> index.html

# Step 6: Restart Apache
service apache2 restart

# Step 7: Exit the Docker container
exit
